apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmops-celeb-detector-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llmops-celeb-detector-repo
  template:
    metadata:
      labels:
        app: llmops-celeb-detector-repo
    spec:
      containers:
      - name: llmops-celeb-detector-repo
        image: us-central1-docker.pkg.dev/atomic-horizon-464016-q9/llmops-celeb-detector-repo
        ports:
        - containerPort: 5000
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: llmops-secrets
              key: GROQ_API_KEY

---

apiVersion: v1
kind: Service
metadata:
  name: llmops-service
spec:
  selector:
    app: llmops-celeb-detector-repo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer